# This is a basic workflow to help you get started with Actions

name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello world"
      - name: Goodbye
        run: echo "Done - Goodbye"
        
      
